baseURL = '/'
languageCode = 'en-uk'
title = 'Geraint Williams'
theme = 'hello-friend'
paginate = 5
publishDir = 'docs'

[params]

  defaultTheme = 'light'
  toc = true

[languages]
  [languages.en]
    title = 'Geraint Williams'
    [languages.en.params.logo]
    logoText = '.'

